services:
  db:
    image: docker.io/library/postgres:15
    container_name: arcade_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-arcade_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-senha_segura_ifsp}
      POSTGRES_DB: ${POSTGRES_DB:-arcade_fight}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  api:
    build: 
      context: ./backend
    container_name: arcade_api
    restart: always
    ports:
      - "80:8001"
    environment:
      - DATABASE_URL= ${DATABASE_URL:-postgresql://arcade_admin:senha_segura_ifsp@db:5432/arcade_fight}
      - APP_URL=${APP_URL:-http://192.168.X.X} 
    depends_on:
      - db

volumes:
  pgdata:
